name = "portfolio-website"
main = "src/server.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { NODE_ENV = "production" }

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "dd61dc10-feb3-4797-9d58-e5c1c67deda4"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "portfolio-media"
